### ISSUE TITLE
Updated theme

### ISSUE THREAD

**Issue by Eragonfr** [nonetallt/vim-neon-dark#1]
Hi, the Sublime Text version of the Neon theme have chnaged quite a lot from when you did this port.  
Do you plan on update this ?

If you don't plan on updating it to a more recent version of the ST theme, did you used a script to convert the theme ? If you used a script can you tell me where I can found it ?

**Comment by nonetallt** [comment]
> Do you plan on update this ?

I'm currently in the process of updating the repository, although my focus is on cleanup and improving syntax highlighting for [nvim treesitter](https://github.com/nvim-treesitter/nvim-treesitter). I might look into how the parent theme has changed, but I'm not planning on prioritizing changing the original colors. 

> If you don't plan on updating it to a more recent version of the ST theme, did you used a script to convert the theme ? If you used a script can you tell me where I can found it ?

Unfortunately there was no such script. I can't remember the exact process I used to extract the color palette but it involved a whole lot of manual work. Although now that you've given me the idea, I might look into the possiblity of creating such a script.

Apologies for the extremely delayed reply, I didn't realize notifications were disabled for this repo - should be fixed now.

**Comment by Eragonfr** [comment]
Thanks for the reply,
I'm using treesitter now, I'm happy to read that you plan on updating to support it better.
